create or replace TRANSIENT TABLE CRICKET.RAW.MATCH_RAW_TBL (
	META OBJECT NOT NULL,
	INFO VARIANT NOT NULL,
	INNINGS ARRAY NOT NULL,
	STG_FILE_NAME VARCHAR(16777216) NOT NULL,
	STG_FILE_ROW_NUMBER NUMBER(38,0) NOT NULL,
	STG_FILE_HASHKEY VARCHAR(16777216) NOT NULL,
	STG_MODIFIED_TS TIMESTAMP_NTZ(9) NOT NULL
)COMMENT='This is raw table to store all the json data file with root elements extracted'
;
