create or replace TABLE CRICKET.PUBLIC.DATE_DIM (
	DATE_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	FULL_DT DATE,
	DAY NUMBER(38,0),
	MONTH NUMBER(38,0),
	YEAR NUMBER(38,0),
	QUARTER NUMBER(38,0),
	DAYOFWEEK NUMBER(38,0),
	DAYOFMONTH NUMBER(38,0),
	DAYOFYEAR NUMBER(38,0),
	DAYOFWEEKNAME VARCHAR(3),
	ISWEEKEND BOOLEAN,
	primary key (DATE_ID)
);
