create or replace TABLE CRICKET.PUBLIC.DELIVERY_FACT (
	MATCH_ID NUMBER(38,0),
	TEAM_ID NUMBER(38,0),
	BOWLER_ID NUMBER(38,0),
	BATTER_ID NUMBER(38,0),
	NON_STIKER_ID NUMBER(38,0),
	OVER NUMBER(38,0),
	RUNS NUMBER(38,0),
	EXTRA_RUNS NUMBER(38,0),
	EXTRA_TYPE VARCHAR(255),
	PLAYER_OUT VARCHAR(255),
	PLAYER_OUT_KIND VARCHAR(255),
	constraint FK_DEL_MATCH_ID foreign key (MATCH_ID) references CRICKET.PUBLIC.MATCH_FACT(MATCH_ID),
	constraint FK_DEL_TEAM foreign key (TEAM_ID) references CRICKET.PUBLIC.TEAM_DIM(TEAM_ID),
	constraint FK_BOWLER foreign key (BOWLER_ID) references CRICKET.PUBLIC.PLAYER_DIM(PLAYER_ID),
	constraint FK_BATTER foreign key (BATTER_ID) references CRICKET.PUBLIC.PLAYER_DIM(PLAYER_ID),
	constraint FK_NON_STRIKER foreign key (NON_STIKER_ID) references CRICKET.PUBLIC.PLAYER_DIM(PLAYER_ID)
);
