create or replace TABLE CRICKET.PUBLIC.REFEREE_DIM (
	REFEREE_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	REFEREE_NAME VARCHAR(16777216) NOT NULL,
	REFEREE_TYPE VARCHAR(16777216) NOT NULL,
	primary key (REFEREE_ID)
);
