create or replace TABLE CRICKET.CLEAN.PLAYER_TABLE_CLEAN (
	MATCH_TYPE_NUMBER NUMBER(38,0),
	TEAM VARCHAR(16777216) NOT NULL,
	PLAYER_NAME VARCHAR(16777216) NOT NULL,
	STG_FILE_NAME VARCHAR(16777216),
	STG_FILE_HASHKEY VARCHAR(16777216),
	STG_FILE_ROW_NUMBER NUMBER(38,0),
	constraint FK_MATCH_ID foreign key (MATCH_TYPE_NUMBER) references CRICKET.CLEAN.MATCH_DETAIL_CLEAN(MATCH_TYPE_NUMBER)
);
